version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: codingriddles
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/codingriddles
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  db_data:
